### PR TITLE
fix bug: App crashes on API level below 21 caused by constructor.

### PR DESCRIPTION
**Pull request by xxjy**

### CODE REVIEW

**Review by PonyCui — APPROVED** [review]

**Comment by daishengda2018** [comment]
About this crash may be due to the default value of defStyleAttr. Please see [《Do not always trust @JvmOverloads》](https://medium.com/@mmlodawski/https-medium-com-mmlodawski-do-not-always-trust-jvmoverloads-5251f1ad2cfe) I will attention this.

**Comment by PonyCui** [comment]
@daishengda2018 Maybe you could provide a PR to avoid crash?

**Comment by daishengda2018** [comment]
> @daishengda2018 Maybe you could provide a PR to avoid crash?
Yes, I will fix and test.

**Comment by daishengda2018** [comment]
This solution was right. 
When i run older code on API 19, I crashed:
image

I found that only the SVGAImageView constructor is called！
image

When i decompile the Kotlin bytecode of SVGAImageView, I found the problem:
image
image

This is because Kotlin @JvmOverloads verride(note that it is override, not overload) superclass’ multiple constructors:
Causes the final 
`SVGAImageView(@NotNull Context context, @Nullable AttributeSet attrs, int defStyleAttr, int defStyleRes) ` to be called.However, below API 21 does not have a construction method for the defstyle attribute. so that it leads to a crash.

So, @PonyCui please publish a fix release,  it‘s very necessary. 
Thanks.

About more information pease see:
[Misconception about Kotlin @JvmOverloads for Android View Creation](https://proandroiddev.com/misconception-about-kotlin-jvmoverloads-for-android-view-creation-cb88f432e1fe)
[A deep dive into Android View constructors](https://blog.danlew.net/2016/07/19/a-deep-dive-into-android-view-constructors/)

**Pull request merged**
